name: update schedule

on:
    schedule:
        - cron: "0 */2 * * *"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: install yarn
              run: npm install yarn -g
            - run: yarn install
            - run: yarn build
            - run: yarn m3u
-            - run: yarn matrix

            - name: "Jekyll theme"
              run: mv ./_config.temp.yml ./m3u/_config.yml

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./m3u
                  enable_jekyll: true
-                 cname: m3u.ibert.me
+                cname: <your-own-domain>

-           - name: discord
-            uses: sebastianpopp/discord-action@releases/v2
-             with:
-                 webhook: ${{ secrets.DISCORD_WEBHOOK }}
-                 message: ${{ github.repository }} has been successfullly updated, see https://m3u.ibert.me to get more.
